name: windows pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set up Go
        run: >
          make all
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dist
          path: dist